#!/usr/bin/env Rscript
# Regenerate theme/_burns-tokens.scss from theme/burns-tokens.yml so the SCSS
# chrome and the R figures share ONE source of colour. Registered as a Quarto
# pre-render step in _quarto.yml; also safe to run by hand:
#   Rscript theme/build-tokens.R
# Pure local transform, no network access.

tok <- yaml::read_yaml(file.path("theme", "burns-tokens.yml"))

kv <- function(prefix, lst) {
  vapply(names(lst), function(k)
    sprintf("$burns-%s%s: %s;", prefix, gsub("_", "-", k), lst[[k]]),
    character(1))
}

lines <- c(
  "// AUTO-GENERATED from theme/burns-tokens.yml by theme/build-tokens.R.",
  "// Do not edit by hand: edit the YAML and re-run (quarto render does this).",
  "",
  sprintf('$burns-font-sans: "%s";', tok$fonts$sans),
  sprintf('$burns-font-mono: "%s";', tok$fonts$mono),
  "",
  "// brand",  kv("", tok$brand),
  "",
  "// light neutrals", kv("light-", tok$light),
  "",
  "// dark neutrals",  kv("dark-",  tok$dark)
)

writeLines(lines, file.path("theme", "_burns-tokens.scss"))
message("Wrote theme/_burns-tokens.scss (", length(tok$brand), " brand tokens)")

# --- Fonts: emit @font-face ONLY for woff2 files that actually exist ----------
# Quarto/dart-sass resolves url() in @font-face at compile time and aborts if a
# referenced file is missing, so a static @font-face block breaks a fresh clone
# that has not added the fonts yet. Generating this file from the fonts present
# on disk keeps the build offline-safe: no fonts -> a comment only (the system
# sans/mono fallback stack in burns.scss handles typography); drop the woff2
# files into theme/fonts/ and re-render -> the faces activate automatically.
font_faces <- data.frame(
  file   = c("IBMPlexSans-Regular.woff2", "IBMPlexSans-Medium.woff2",
             "IBMPlexSans-SemiBold.woff2", "IBMPlexSans-Bold.woff2",
             "IBMPlexMono-Regular.woff2", "IBMPlexMono-Medium.woff2"),
  family = c(rep(tok$fonts$sans, 4), rep(tok$fonts$mono, 2)),
  weight = c(400, 500, 600, 700, 400, 500),
  stringsAsFactors = FALSE
)
present <- file.exists(file.path("theme", "fonts", font_faces$file))
font_lines <- c(
  "// AUTO-GENERATED by theme/build-tokens.R from the woff2 files present in",
  "// theme/fonts/. Do not edit by hand. Missing fonts fall back to the system",
  "// sans/mono stack declared in burns.scss, so the build stays offline-safe.",
  ""
)
if (any(present)) {
  font_lines <- c(font_lines, vapply(which(present), function(i) sprintf(
    paste0('@font-face { font-family: "%s"; font-style: normal; font-weight: %d; ',
           'font-display: swap; src: url("theme/fonts/%s") format("woff2"); }'),
    font_faces$family[i], font_faces$weight[i], font_faces$file[i]
  ), character(1)))
} else {
  font_lines <- c(font_lines,
    "// No woff2 files found in theme/fonts/ yet; using system fallback fonts.")
}
writeLines(font_lines, file.path("theme", "_burns-fonts.scss"))
message("Wrote theme/_burns-fonts.scss (", sum(present), "/", nrow(font_faces),
        " font faces present)")
